#-----------------------------#
# Surival Games by humandavey #
#-----------------------------#

max-players: 16
min-players: 2

facing: "world;45.5;67;251.5"

spawnpoints:
  - "world;48.5;69;257.5"
  - "world;50.5;69;256.5"
  - "world;51.5;69;254.5"
  - "world;51.5;69;251.5"
  - "world;51.5;69;248.5"
  - "world;50.5;69;246.5"
  - "world;48.5;69;245.5"
  - "world;45.5;69;245.5"
  - "world;42.5;69;245.5"
  - "world;40.5;69;246.5"
  - "world;39.5;69;248.5"
  - "world;39.5;69;251.5"
  - "world;39.5;69;254.5"
  - "world;40.5;69;256.5"
  - "world;42.5;69;257.5"
  - "world;45.5;69;257.5"

chest-locations:
  - "world;45;65;251"

placeable-blocks:
  - "CRAFTING_TABLE"

breakable-blocks:
  - "GRASS"
  - "TALL_GRASS"

messages:
  no-permission: "&cYou don't have permission to use this command!"
  player-joined: "&7%player% &ejoined the game! (&b%num%&e/&b%max%&e)"
  game-started: "&aThe battle has begun!"
  countdown-cancelled: "&cThe countdown has been cancelled!"
  player-left: "&7%player% &equit the game! (&b%num%&e/&b%max%&e)"
  already-begun: "&cThe game has already begun!"